{% set version = "1.1" %}

package:
    name: ismip6_antarctic_ocean_forcing
    version: {{ version }}

source:
    path: ..

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    noarch: python

requirements:
    host:
        - python >=3.6
        - pip
    run:
        - python >=3.6
        - dask
        - descartes
        - gsw
        - imageio
        - matplotlib
        - nco
        - netcdf4
        - numpy
        - progressbar2
        - pyremap<0.1.0
        - pyshp
        - requests
        - scikit-fmm
        - scipy
        - shapely
        - xarray

test:
    requires:
        - pip
    imports:
        - ismip6_ocean_forcing
    commands:
        - ismip6_ocean_forcing --version
        - pip check


about:
    home:  https://github.com/ismip/ismip6-antarctic-ocean-forcing
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: 'A python package for creating ISMIP6 ocean forcing data sets.'

extra:
    recipe-maintainers:
        - xylar

